const ORDER_STATUS = {
  PENDING: 0,
  DRIVER_ACCEPT: 1,
  DEPARTURE_TO_CUSTOMER: 2,
  ARRIVAL_AT_CUSTOMER: 3,
  DEPARTURE_TO_DESTINATION: 5,
  ARRIVAL_AT_DESTINATION: 6,
  COMPLETE: 7,
  CANCEL: 8,
};

const USER_STATUS = {
  INACTIVE: 0,
  ACTIVE: 1,
};

const DRIVER_ORDER_STATUS = {
  OFFLINE: 'offline',
  ONLINE: 'online',
};

const RATING_TYPE = {
  CUSTOMER_TO_DRIVER: 1,
  DRIVER_TO_CUSTOMER: 2,
};

const PAYMENT_METHOD = {
  CASH: 'cash',
  CARD: 'card',
  WALLET: 'wallet',
};

const PAYMENT_STATUS = {
  PENDING: 0,
  SUCCESS: 1,
  CANCEL: 2,
};

const LOGIN_TYPE = {
  APP: 'app',
  SOCIAL: 'social',
};

module.exports = {
  ORDER_STATUS,
  USER_STATUS,
  DRIVER_ORDER_STATUS,
  RATING_TYPE,
  PAYMENT_METHOD,
  PAYMENT_STATUS,
  LOGIN_TYPE,
};
